apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxtest
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - name: nginxtest
        image: coreharbor.tebelabk3s.lyr.id/public/nginxtest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginxtest
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginxtest


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxtest-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - nginxtest.tebelabk3s.lyr.id
    secretName: nginxtest-tls
  rules:
  - host: nginxtest.tebelabk3s.lyr.id
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginxtest
            port:
              number: 80
