name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          docker login https://coreharbor.tebelabk3s.lyr.id -u admin -p V3WTOnHt2uJ92e0ydElfrI9K7dUFIfq
          docker build -t coreharbor.tebelabk3s.lyr.id/public/nginxtest:latest .
          docker push coreharbor.tebelabk3s.lyr.id/public/nginxtest:latest
