name: CI Docker Image Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Tag is full commit SHA
      - name: Set commitid as image tag
        id: tag
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t teguhbudhi13/nginx:${TAG} .

      # --- Trivy Scan (JSON Output) ---
      - name: Trivy Scan (JSON Output)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: teguhbudhi13/nginx:${{ env.TAG }}
          format: json
          output: trivy-results.json
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Show Critical/High from Trivy
        id: trivy-count
        run: |
          CRITICAL=$(jq '[.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | select(.Severity=="CRITICAL")] | length' trivy-results.json)
          HIGH=$(jq '[.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | select(.Severity=="HIGH")] | length' trivy-results.json)
          echo "CRITICAL found by Trivy: $CRITICAL"
          echo "HIGH found by Trivy: $HIGH"
          echo "critical_count=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high_count=$HIGH" >> $GITHUB_OUTPUT
          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "Trivy found critical/high vulnerabilities. Failing."
            exit 1
          fi

      - name: Show Fix Details for Trivy CRITICAL/HIGH
        if: always()
        run: |
          echo "Vulnerabilities with available fixes (CRITICAL/HIGH):"
          jq -r '
            .Results[]
            | select(.Vulnerabilities != null)
            | .Vulnerabilities[]
            | select(.Severity=="CRITICAL" or .Severity=="HIGH")
            | select(.FixedVersion != null and .FixedVersion != "" and .FixedVersion != "-")
            | "\(.PkgName)\t\(.InstalledVersion)\t\(.VulnerabilityID)\t\(.Severity)\t\(.FixedVersion)"
          ' trivy-results.json | \
          awk 'BEGIN {print "PkgName\tCurrent\tCVE\tSeverity\tFixedVersion"} {print $0}'

      # --- Install Docker Scout ---
      - name: Install Docker Scout
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin

      # --- Docker Scout CVEs scan (SARIF Output) ---
      - name: Docker Scout CVEs scan
        run: |
          docker scout cves teguhbudhi13/nginx:${TAG} --format sarif --output scout-results.sarif > scout.log || true
          CRITICAL=$(grep -c '✗ CRITICAL' scout.log || true)
          HIGH=$(grep -c '✗ HIGH' scout.log || true)
          echo "CRITICAL found by Docker Scout: $CRITICAL"
          echo "HIGH found by Docker Scout: $HIGH"
          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "Docker Scout found critical/high vulnerabilities. Failing."
            exit 1
          fi

      # --- Docker Scout Recommendations ---
      - name: Docker Scout Recommendations
        run: docker scout recommendations teguhbudhi13/nginx:${TAG}

      # --- Push to DockerHub (if all checks passed) ---
      - name: Push image to DockerHub
        run: docker push teguhbudhi13/nginx:${TAG}
